"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.move = exports.add = exports.remove = exports.unshift = exports.shift = exports.pop = exports.push = exports.slice = exports.filterFirstItemGetKey = exports.filterFirstItem = exports.getFirstItem = exports.sort = exports.filter = exports.join = exports.split = exports.match = exports.map = exports.isFirstItem = exports.createArray = exports.argsToArray = exports.isEmptyArray = exports.isArray = exports.runFnOfObj = exports.log = exports.isNullOrUndefined = exports.runIfHasProperty = exports.runIfType = exports.checkTypeOfValue = exports.ifThenElse = exports.defaultFn = exports.ifTypeError = exports.addLogging = exports.tryer = exports.makeAsyncCall = exports.localNumberString = exports.rest = exports.div = exports.minus = exports.plus = exports.mult = exports.replaceNullValuesInObject = exports.stringComparator = exports.dateComparator = exports.isDevEnvironment = exports.isObject = exports.addKey = exports.addKeyFunc = exports.getObjKeys = exports.getKey = exports.checkObjectForProperty = void 0;
exports.mid = exports.right = exports.left = exports.append = exports.prepend = exports.strFill = exports.str = exports.replace = exports.capitalize = exports.upperCase = void 0;
var object_functions_1 = require("./objects/object-functions");
Object.defineProperty(exports, "checkObjectForProperty", { enumerable: true, get: function () { return object_functions_1.checkObjectForProperty; } });
Object.defineProperty(exports, "getKey", { enumerable: true, get: function () { return object_functions_1.getKey; } });
Object.defineProperty(exports, "getObjKeys", { enumerable: true, get: function () { return object_functions_1.getObjKeys; } });
Object.defineProperty(exports, "addKeyFunc", { enumerable: true, get: function () { return object_functions_1.addKeyFunc; } });
Object.defineProperty(exports, "addKey", { enumerable: true, get: function () { return object_functions_1.addKey; } });
Object.defineProperty(exports, "isObject", { enumerable: true, get: function () { return object_functions_1.isObject; } });
Object.defineProperty(exports, "replaceNullValuesInObject", { enumerable: true, get: function () { return object_functions_1.replaceNullValuesInObject; } });
var number_functions_1 = require("./numbers/number-functions");
Object.defineProperty(exports, "mult", { enumerable: true, get: function () { return number_functions_1.mult; } });
Object.defineProperty(exports, "plus", { enumerable: true, get: function () { return number_functions_1.plus; } });
Object.defineProperty(exports, "minus", { enumerable: true, get: function () { return number_functions_1.minus; } });
Object.defineProperty(exports, "div", { enumerable: true, get: function () { return number_functions_1.div; } });
Object.defineProperty(exports, "rest", { enumerable: true, get: function () { return number_functions_1.rest; } });
Object.defineProperty(exports, "localNumberString", { enumerable: true, get: function () { return number_functions_1.localNumberString; } });
var higher_order_funtions_1 = require("./higher-order/higher-order-funtions");
Object.defineProperty(exports, "makeAsyncCall", { enumerable: true, get: function () { return higher_order_funtions_1.makeAsyncCall; } });
Object.defineProperty(exports, "tryer", { enumerable: true, get: function () { return higher_order_funtions_1.tryer; } });
Object.defineProperty(exports, "addLogging", { enumerable: true, get: function () { return higher_order_funtions_1.addLogging; } });
Object.defineProperty(exports, "ifTypeError", { enumerable: true, get: function () { return higher_order_funtions_1.ifTypeError; } });
Object.defineProperty(exports, "defaultFn", { enumerable: true, get: function () { return higher_order_funtions_1.defaultFn; } });
Object.defineProperty(exports, "ifThenElse", { enumerable: true, get: function () { return higher_order_funtions_1.ifThenElse; } });
Object.defineProperty(exports, "checkTypeOfValue", { enumerable: true, get: function () { return higher_order_funtions_1.checkTypeOfValue; } });
Object.defineProperty(exports, "runIfType", { enumerable: true, get: function () { return higher_order_funtions_1.runIfType; } });
Object.defineProperty(exports, "runIfHasProperty", { enumerable: true, get: function () { return higher_order_funtions_1.runIfHasProperty; } });
Object.defineProperty(exports, "isNullOrUndefined", { enumerable: true, get: function () { return higher_order_funtions_1.isNullOrUndefined; } });
Object.defineProperty(exports, "log", { enumerable: true, get: function () { return higher_order_funtions_1.log; } });
Object.defineProperty(exports, "runFnOfObj", { enumerable: true, get: function () { return higher_order_funtions_1.runFnOfObj; } });
var array_functions_1 = require("./arrays/array-functions");
Object.defineProperty(exports, "isArray", { enumerable: true, get: function () { return array_functions_1.isArray; } });
Object.defineProperty(exports, "isEmptyArray", { enumerable: true, get: function () { return array_functions_1.isEmptyArray; } });
Object.defineProperty(exports, "argsToArray", { enumerable: true, get: function () { return array_functions_1.argsToArray; } });
Object.defineProperty(exports, "createArray", { enumerable: true, get: function () { return array_functions_1.createArray; } });
Object.defineProperty(exports, "isFirstItem", { enumerable: true, get: function () { return array_functions_1.isFirstItem; } });
Object.defineProperty(exports, "map", { enumerable: true, get: function () { return array_functions_1.map; } });
Object.defineProperty(exports, "match", { enumerable: true, get: function () { return array_functions_1.match; } });
Object.defineProperty(exports, "split", { enumerable: true, get: function () { return array_functions_1.split; } });
Object.defineProperty(exports, "join", { enumerable: true, get: function () { return array_functions_1.join; } });
Object.defineProperty(exports, "filter", { enumerable: true, get: function () { return array_functions_1.filter; } });
Object.defineProperty(exports, "sort", { enumerable: true, get: function () { return array_functions_1.sort; } });
Object.defineProperty(exports, "getFirstItem", { enumerable: true, get: function () { return array_functions_1.getFirstItem; } });
Object.defineProperty(exports, "filterFirstItem", { enumerable: true, get: function () { return array_functions_1.filterFirstItem; } });
Object.defineProperty(exports, "filterFirstItemGetKey", { enumerable: true, get: function () { return array_functions_1.filterFirstItemGetKey; } });
Object.defineProperty(exports, "slice", { enumerable: true, get: function () { return array_functions_1.slice; } });
Object.defineProperty(exports, "push", { enumerable: true, get: function () { return array_functions_1.push; } });
Object.defineProperty(exports, "pop", { enumerable: true, get: function () { return array_functions_1.pop; } });
Object.defineProperty(exports, "shift", { enumerable: true, get: function () { return array_functions_1.shift; } });
Object.defineProperty(exports, "unshift", { enumerable: true, get: function () { return array_functions_1.unshift; } });
Object.defineProperty(exports, "remove", { enumerable: true, get: function () { return array_functions_1.remove; } });
Object.defineProperty(exports, "add", { enumerable: true, get: function () { return array_functions_1.add; } });
Object.defineProperty(exports, "move", { enumerable: true, get: function () { return array_functions_1.move; } });
var string_functions_1 = require("./strings/string-functions");
Object.defineProperty(exports, "upperCase", { enumerable: true, get: function () { return string_functions_1.upperCase; } });
Object.defineProperty(exports, "capitalize", { enumerable: true, get: function () { return string_functions_1.capitalize; } });
Object.defineProperty(exports, "replace", { enumerable: true, get: function () { return string_functions_1.replace; } });
Object.defineProperty(exports, "str", { enumerable: true, get: function () { return string_functions_1.str; } });
Object.defineProperty(exports, "strFill", { enumerable: true, get: function () { return string_functions_1.strFill; } });
Object.defineProperty(exports, "prepend", { enumerable: true, get: function () { return string_functions_1.prepend; } });
Object.defineProperty(exports, "append", { enumerable: true, get: function () { return string_functions_1.append; } });
Object.defineProperty(exports, "left", { enumerable: true, get: function () { return string_functions_1.left; } });
Object.defineProperty(exports, "right", { enumerable: true, get: function () { return string_functions_1.right; } });
Object.defineProperty(exports, "mid", { enumerable: true, get: function () { return string_functions_1.mid; } });
var other_functions_1 = require("./extras/other-functions");
Object.defineProperty(exports, "isDevEnvironment", { enumerable: true, get: function () { return other_functions_1.isDevEnvironment; } });
var comparators_1 = require("./extras/comparators");
Object.defineProperty(exports, "dateComparator", { enumerable: true, get: function () { return comparators_1.dateComparator; } });
Object.defineProperty(exports, "stringComparator", { enumerable: true, get: function () { return comparators_1.stringComparator; } });
