export declare const upperCase: (val: string | any) => any;
export declare const capitalize: (str: string) => string;
export declare const replace: (toReplace: string, replacyBy: string) => (str: string) => string;
export declare const str: (str: string) => () => string;
export declare const strFill: (fill: string, digits: number) => (str: string) => string;
export declare const prepend: (pre: string) => (str: string) => string;
export declare const append: (post: string) => (str: string) => string;
export declare const left: (count: number) => (str: string) => string;
export declare const right: (count: number) => (str: string) => string;
export declare const mid: (first: number, length: number) => (str: string) => string;
